// Generated by reverb_model.py; do not edit. What the reverb must produce for each case, from a model
// of the console written apart from the C.
#ifndef MODEL_FINGERPRINTS_H
#define MODEL_FINGERPRINTS_H

#include <stdint.h>

enum { MODEL_TICKS = 55125 };

typedef struct model_case
{
    int mode, delay, feedback, shift, later_mode, later_delay;
    uint64_t fingerprint;
} model_case;

static const model_case model_cases[] = {
    {0, -1, -1, 0, -1, -1, 0x37440F6677120235ull},
    {0, -1, -1, 3, -1, -1, 0x37440F6677120235ull},
    {1, -1, -1, 0, -1, -1, 0xA9A3860053D2CDE6ull},
    {1, -1, -1, 3, -1, -1, 0x2DDE39D056D47985ull},
    {2, -1, -1, 0, -1, -1, 0xD9ECE34310929E6Cull},
    {2, -1, -1, 3, -1, -1, 0x5ACF4F4790E4D549ull},
    {3, -1, -1, 0, -1, -1, 0x28A549397085F529ull},
    {3, -1, -1, 3, -1, -1, 0x0AB6E83788264123ull},
    {4, -1, -1, 0, -1, -1, 0xD1684380C155D13Cull},
    {4, -1, -1, 3, -1, -1, 0x0F0CE4E1D6BAA9C7ull},
    {5, -1, -1, 0, -1, -1, 0xD7E69E6F7DFCA0FEull},
    {5, -1, -1, 3, -1, -1, 0x59795A69A6901A3Dull},
    {6, -1, -1, 0, -1, -1, 0x17423F653F2EA398ull},
    {6, -1, -1, 3, -1, -1, 0x23B38AAC7C2E6FCBull},
    {7, -1, -1, 0, -1, -1, 0x69DBFCDE5907773Cull},
    {7, -1, -1, 3, -1, -1, 0xAE8E573407E5F8BDull},
    {8, -1, -1, 0, -1, -1, 0x6256AD0909184047ull},
    {8, -1, -1, 3, -1, -1, 0x1BD6BD6BA0C96D73ull},
    {9, -1, -1, 0, -1, -1, 0xF228BB3AB5760D62ull},
    {9, -1, -1, 3, -1, -1, 0xC56504E1C30CFC98ull},
    {7, 64, 100, 3, -1, -1, 0x3C4392B51C98C1F9ull},
    {7, 1, 127, 3, -1, -1, 0xA40D9CC2C0616407ull},
    {7, 127, 126, 3, -1, -1, 0x359DC8249112D798ull},
    {7, 40, 30, 0, -1, -1, 0xF051870CE1A9D54Eull},
    {8, 30, -1, 3, -1, -1, 0x8FEA38D38824A3A1ull},
    {5, -1, -1, 3, 1, -1, 0x02C42AF492D10E93ull},
    {7, -1, -1, 3, -1, 40, 0xBEB6E1983191DE80ull},
    {8, -1, -1, 0, 7, -1, 0x0050E27181A444D1ull},
};

enum { MODEL_UNIT_TICKS = 110250 };

typedef struct model_unit_case
{
    int mode, delay, feedback, shift, later_mode, later_delay, depth_left, depth_right;
    uint64_t fingerprint;
} model_unit_case;

static const model_unit_case model_unit_cases[] = {
    {0, -1, -1, 3, -1, -1, 32767, 32767, 0xB8650AED8665EE45ull},
    {1, -1, -1, 3, -1, -1, 32767, 32767, 0x86A9B1BFC6E05875ull},
    {2, -1, -1, 3, -1, -1, 32767, 32767, 0x649A47442979783Aull},
    {3, -1, -1, 3, -1, -1, 32767, 32767, 0x22DA8453FC69306Aull},
    {4, -1, -1, 3, -1, -1, 32767, 32767, 0x28526EE83F1932F8ull},
    {5, -1, -1, 3, -1, -1, 32767, 32767, 0x59663569875CEFFEull},
    {6, -1, -1, 3, -1, -1, 32767, 32767, 0x5A6FDAB96F748F2Dull},
    {7, -1, -1, 3, -1, -1, 32767, 32767, 0x805E49D10C5380EBull},
    {8, -1, -1, 3, -1, -1, 32767, 32767, 0x8D039D90FADD9FF0ull},
    {9, -1, -1, 3, -1, -1, 32767, 32767, 0x56072D2514E3FB06ull},
    {1, -1, -1, 0, -1, -1, 32767, -32768, 0xC8767ECB560266CAull},
    {5, -1, -1, 0, -1, -1, -32768, 16384, 0xAAB70CA583940E5Aull},
    {9, -1, -1, 0, -1, -1, 12288, 32767, 0xDBF79D2C7FD923FBull},
    {7, 64, 100, 3, -1, -1, 16383, 8192, 0xABB8249FF2CD73D5ull},
    {5, -1, -1, 3, 1, -1, 32767, 32767, 0x6628815DCF0A2F99ull},
    {7, -1, -1, 3, -1, 40, 32767, 32767, 0xD46D0873D966DCE7ull},
};

#endif
