name: Native

on:
  push:
  pull_request:

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: Native~
    steps:
      - uses: actions/checkout@v5
      - run: cmake --preset debug
      - run: cmake --build --preset debug
      - run: ctest --preset debug
      - run: cmake --preset release
      - run: cmake --build --preset release
      - run: ctest --preset release
